- name: install packages
  apt:
    update_cache: yes
    cache_valid_time: 7200
    name:
      - fonts-vlgothic
      - python3-pip
      - python3-pil
  become: yes

- name: install inky library
  pip:
    name: inky
    virtualenv: "{{ venv_dir }}"
    virtualenv_command: "{{ ansible_python_interpreter }} -m venv --system-site-packages {{ venv_dir }}"

- name: ensure create directory
  file:
    path: /usr/share/fonts/truetype/
    state: directory
  become: yes

- name: install fonts
  get_url:
    url: "{{ item }}"
    dest: /usr/share/fonts/truetype/
  loop:
  - http://www17.plala.or.jp/xxxxxxx/00ff/x14y24pxHeadUpDaisy.ttf
  - http://www17.plala.or.jp/xxxxxxx/00ff/x8y12pxTheStrongGamer.ttf
  become: yes

- name: create directory for tenki
  file:
    path: "/home/{{ ansible_user }}/tenki"
    state: directory

- name: copy scripts
  copy:
    src: "tenki/{{ item }}"
    dest: "/home/{{ ansible_user }}/tenki"
  loop:
  - tenki.py
  - tenki-base.png
  - sunny.png
  - cloudy.png
  - rain.png
  - snow.png
