- name: install debian packages
  apt:
    name:
    - python3-pip
    - python3-dev
    - sense-hat
    - python3-pil
    state: present
  become: yes

- name: install python pyowm modules
  pip:
    name: pyowm
    state: present
  become: yes

- name: copy scripts
  template:
    src: japan_weather_sensehat.py
    dest: /home/pi/japan_weather_sensehat.py
    owner: pi
    group: pi
    mode: 0755

