- name: install debian packages
  apt:
    name:
    - python-pip
    - python-dev
    - sense-hat
    - python-pil
    state: present
  become: yes

- name: install python pyowm modules
  pip:
    name: pyowm
    state: present
  become: yes

- name: copy scripts
  template:
    src: japan_weather_sensehat.py
    dest: /home/pi/japan_weather_sensehat.py
    owner: pi
    group: pi
    mode: 0755

- name: enable i2c
  command: raspi-config nonint do_i2c 0
  become: yes
