- name: install packages
  apt:
    name:
      - cups
      - python3-minimal
      - python3-pip
      - python3-rpi.gpio
    state: present
  become: yes

- name: install escpos
  pip:
    name:
    - python-escpos
    - Mastodon.py
    state: present
    executable: /usr/bin/pip3
  become: yes

- name: copy systemd script
  copy:
    src: "profile-print.service"
    dest: "/etc/systemd/system/profile-print.service"
  become: yes

- name: copy profile_print script
  copy:
    src: profile_print
    dest: /home/pi/
    mode: 0755

- name: enable and start service
  systemd:
    name: "profile-print"
    daemon-reload: yes
    enabled: yes
    state: started
  become: yes
