- name: run ldconfig
  command: ldconfig
  become: yes

- name: reload udev
  command: udevadm control --reload-rules
  become: yes

- name: restart lcd-icreader
  systemd:
    name: lcd-icreader
    state: restarted
  become: yes