- set_fact: 
    vim_ver: vim80
  when: ansible_distribution_release == "stretch"

- set_fact: 
    vim_ver: vim81
  when: ansible_distribution_release == "buster"

- set_fact: 
    vim_ver: vim82
  when: ansible_distribution_release == "bullseye"

- set_fact: 
    vim_ver: vim90
  when: ansible_distribution_release == "bookworm"

- name: install vim
  apt:
    update_cache: yes
    cache_valid_time: 7200
    name: vim
    state: present
  become: yes

- name: disable mouse
  replace:
    path: "/usr/share/vim/{{ vim_ver }}/defaults.vim"
    regexp: '^([ ]+)set mouse=a'
    replace: '"\1set mouse=a'
  become: yes

- name: disable auto indent
  replace:
    path: "/usr/share/vim/{{ vim_ver }}/defaults.vim"
    regexp: "filetype plugin indent on"
    replace: "filetype plugin indent off"
  become: yes

- name: disable scrolloff
  replace:
    path: "/usr/share/vim/{{ vim_ver }}/defaults.vim"
    regexp: "scrolloff=5"
    replace: "scrolloff=0"
  become: yes
