- name: disable RTL8192CU power mgmt & auto suspend
  lineinfile:
    path: /etc/modprobe.d/8192cu.conf
    line: "options 8192cu rtw_power_mgnt=0 rtw_enusbss=0"
    state: present
    create: yes
  become: yes

- name: check network-manager is installed
  stat:
    path: /etc/NetworkManager/NetworkManager.conf
  register: nmconf

- name: disable wifi.scan-rand-mac-address if network-manager is installed
  blockinfile:
    path: /etc/NetworkManager/NetworkManager.conf
    block: |
      
      [device]
      wifi.scan-rand-mac-address=no
  when: nmconf.stat.exists
  become: yes
