- name: disable RTL8192CU power mgmt & auto suspend
  lineinfile: >
    dest=/etc/modprobe.d/8192cu.conf
    line="options 8192cu rtw_power_mgnt=0 rtw_enusbss=0"
    state=present
    create=yes
  sudo: yes
