# うちではこのプログラムによって毎朝CD-ROMドライブがEjectして
# カーテンが開くことになっているが、他の家庭にそんなものはないはずなので
# Lチカのサンプルくらいに思ってもらえれば。
- name: curtain
  hosts: all
  gather_facts: no
  vars:
    - rungpio: |
        #!/bin/bash
        gpio -g mode 17 out
        gpio -g write 17 1
        sleep 0.1
        gpio -g write 17 0
  tasks:
    - name: install packages
      apt:
        name: wiringpi
        state: present
      become: true

    - name: copy rungpio.sh
      copy:
        content: "{{ rungpio }}"
        dest: /home/pi/rungpio.sh
        mode: 0755

    - name: set cron job
      cron:
        name: morning
        hour: 6
        minute: 0
        job: "/home/pi/rungpio.sh ; sleep 5 ; /home/pi/rungpio.sh"
        state: present
