# うちではこのプログラムによって毎朝CD-ROMドライブがEjectして
# カーテンが開くことになっているが、他の家庭にそんなものはないはずなので
# Lチカのサンプルくらいに思ってもらえれば。
- name: curtain
  hosts: all
  gather_facts: no
  vars:
    - rungpio: |
        #!/bin/bash
        pinctrl set 23 op pn dh
        sleep 0.1
        pinctrl set 23 op pn dl
  tasks:
    - name: copy rungpio.sh
      copy:
        content: "{{ rungpio }}"
        dest: "/home/{{ ansible_user }}/rungpio.sh"
        mode: 0755

    - name: set cron job
      cron:
        name: morning
        hour: 6
        minute: 0
        job: "/home/{{ ansible_user }}/rungpio.sh ; sleep 5 ; /home/{{ ansible_user }}/rungpio.sh"
        state: present
