- name: add apt repositry jessie
  apt_repository: >
    repo='deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi'
    state=present
  sudo: yes

- name: copy /etc/apt/preferences
  copy: >
    src=preferences
    dest=/etc/apt/preferences
    owner=root
    group=root
    mode=0644
  sudo: yes