---
# Raspbianにドライバーコンパイル環境を作るPlaybook
# ベースにした→ http://qnighy.hatenablog.com/entry/2015/02/05/155016

hosts: raspi

vars:
  preferences: |
Package: *
Pin: release n=wheezy
Pin-Priority: 900

Package: *
Pin: release n=jessie
Pin-Priority: 300

Package: *
Pin: release o=Raspbian
Pin-Priority: -10

tasks:
  - name: add apt repositry jessie
    apt_repository: >
      repo='deb http://mirrordirector.raspbian.org/raspbian/ jessie main contrib non-free rpi'
      state=present
    sudo: yes
  
  - name: copy /etc/apt/preferences
    copy: >
      content: {{ preferences }}
      dest=/etc/apt/preferences
      owner=root
      group=root
      mode=0644
    sudo: yes
  
  - name: install gcc-4.8/jessie
    apt: >
      default_release=jessie
      name={{ item }}
      state=present
      update_cache=yes
      cache_valid_time=3600
    with_items:
      - gcc-4.8
      - gcc-4.8-base
      - cpp-4.8
      - binutils
      - libgcc-4.8-dev
      - libgcc1
      - libmpfr4
      - libatomic1
      - libasan0
      - libstdc++6
      - libgomp1
      - libc6
      - libc6-dev
    sudo: yes
    
  - name: install other packeages
    apt: >
      name=libncurses5-dev
      state=present
    sudo: yes
  
  - name: mark as auto-installed packages
    command: apt-mark auto libmpfr4 cpp-4.8 libgcc-4.8-dev libgcc1 libc6-dev libc-dev-bin libc6
    sudo: yes
  
  - name: set alternatives
    alternatives: >
      name=gcc
      path=/usr/bin/gcc-4.8
      link=/usr/bin/gcc
    sudo: yes
  
  - name: download rpi-source
    get_url: >
      url=https://raw.githubusercontent.com/notro/rpi-source/master/rpi-source
      dest=/usr/bin/rpi-source
      mode=0755
    sudo: yes
  
  - name: rpi-source tag update
    command: /usr/bin/rpi-source -q --tag-update
    sudo: yes
  
  - name: run rpi-source
    command: rpi-source
